### ISSUE TITLE
number of files produced in s3 per spark application?

### ISSUE THREAD

**Issue by cpd85** [IBM/spark-s3-shuffle#6]
Hi there, thanks for creating this repo! I had a question about an upper bound or estimate on files created in s3 by this shuffle manager. As far as I can tell, each map task gets a partition writer for each partition and then at the end of the task all of these partition files are flushed to s3. This would give a bound of (numMaps * numPartitions) -- am I accurate here?

**Comment by pspoerri** [comment]
@cpd85 no. I merge the partitions into the same file for each map. The maximum number of shuffle files is `2*numMaps` (1x Index file, 1x data file). If a shuffle is empty, then I don't create any data.

This can be seen here: https://github.com/IBM/spark-s3-shuffle/blob/main/src/main/scala/org/apache/spark/shuffle/S3BypassMergeSortShuffleWriter.scala#L119-L155

The shuffle blocks for each partition are first cached locally and then merged+written to S3.
