### ISSUE TITLE
3.5.1 support?

### ISSUE THREAD

**Issue by 8enmann** [IBM/spark-s3-shuffle#83]
Latest release appears to support up to 3.4.0
https://github.com/IBM/spark-s3-shuffle/releases

Possible to do a new release for 3.5.1? If you give me some pointers I'd be happy to try it.

**Comment by leovegas** [comment]
It works with 3.5.0 for me.

**Comment by 8enmann** [comment]
Ah will try it! Did you use the 3.4.0 release?

**Comment by pspoerri** [comment]
Sorry, somehow I have issues getting public github notifications.
The 3.4.0 build should work: The Spark API did not change. I'll add a 3.5.x build for consistency.

**Comment by pspoerri** [comment]
Builds should be available in a couple minutes: https://github.com/IBM/spark-s3-shuffle/releases/tag/v0.9.6
